/*
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("bdroussi/nkouadio/tl/tp2/parser/antlr/internal/InternalWL.tokens");
	}
}
