/*
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2.parser.antlr;

import bdroussi.nkouadio.tl.tp2.parser.antlr.internal.InternalWLParser;
import bdroussi.nkouadio.tl.tp2.services.WLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class WLParser extends AbstractAntlrParser {

	@Inject
	private WLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWLParser createParser(XtextTokenStream stream) {
		return new InternalWLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public WLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
