/*
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2.ide;

import bdroussi.nkouadio.tl.tp2.WLRuntimeModule;
import bdroussi.nkouadio.tl.tp2.WLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WLIdeSetup extends WLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WLRuntimeModule(), new WLIdeModule()));
	}
	
}
