/*
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WLRuntimeModule extends AbstractWLRuntimeModule {
}
