/*
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WLStandaloneSetup extends WLStandaloneSetupGenerated {

	public static void doSetup() {
		new WLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
