/*
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WLUiModule extends AbstractWLUiModule {

	public WLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
