/**
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2.wL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link bdroussi.nkouadio.tl.tp2.wL.Program#getFunctions <em>Functions</em>}</li>
 * </ul>
 *
 * @see bdroussi.nkouadio.tl.tp2.wL.WLPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Functions</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' attribute list.
   * @see bdroussi.nkouadio.tl.tp2.wL.WLPackage#getProgram_Functions()
   * @model unique="false"
   * @generated
   */
  EList<String> getFunctions();

} // Program
