/**
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2.wL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see bdroussi.nkouadio.tl.tp2.wL.WLFactory
 * @model kind="package"
 * @generated
 */
public interface WLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "wL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.nkouadio.bdroussi/tl/tp2/WL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "wL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WLPackage eINSTANCE = bdroussi.nkouadio.tl.tp2.wL.impl.WLPackageImpl.init();

  /**
   * The meta object id for the '{@link bdroussi.nkouadio.tl.tp2.wL.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see bdroussi.nkouadio.tl.tp2.wL.impl.ProgramImpl
   * @see bdroussi.nkouadio.tl.tp2.wL.impl.WLPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FUNCTIONS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link bdroussi.nkouadio.tl.tp2.wL.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see bdroussi.nkouadio.tl.tp2.wL.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute list '{@link bdroussi.nkouadio.tl.tp2.wL.Program#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Functions</em>'.
   * @see bdroussi.nkouadio.tl.tp2.wL.Program#getFunctions()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Functions();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WLFactory getWLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link bdroussi.nkouadio.tl.tp2.wL.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see bdroussi.nkouadio.tl.tp2.wL.impl.ProgramImpl
     * @see bdroussi.nkouadio.tl.tp2.wL.impl.WLPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__FUNCTIONS = eINSTANCE.getProgram_Functions();

  }

} //WLPackage
