/*
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2.ui.tests;

import bdroussi.nkouadio.tl.projetWH.ui.internal.ProjetWHActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class WLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProjetWHActivator.getInstance().getInjector("bdroussi.nkouadio.tl.tp2.WL");
	}

}
