/*
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2.ui;

import bdroussi.nkouadio.tl.projetWH.ui.internal.ProjetWHActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ProjetWHActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ProjetWHActivator activator = ProjetWHActivator.getInstance();
		return activator != null ? activator.getInjector(ProjetWHActivator.BDROUSSI_NKOUADIO_TL_TP2_WL) : null;
	}

}
