/*
 * generated by Xtext 2.24.0
 */
package bdroussi.nkouadio.tl.tp2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWLScopeProvider extends DelegatingScopeProvider {
}
